name: First Workflow
 
on:
push:
branches: [ master ]
pull_request:
branches: [ master ]
workflow_dispatch: # manual trigger
schedule:
- cron: "40 12 * * *"  # Runs daily at 3:30 AM UTC
 
jobs:
build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v5.0.0
  - name: Setup Node Js
    uses: actions/setup-node@v5
    with:
        node-version: lts/*
  - name: Install dependencies
    run: npm ci
  - name: Install Playwright Browsers
    run: npx playwright install --with-deps
  - name: Run Playwright tests
    run: npx playwright test
  - uses: actions/upload-artifact@v4
    if: ${{ !cancelled() }}
    with:
      name: playwright-report
      path: playwright-report/
      retention-days: 30
